## syntax=docker/dockerfile:1.7-labs
FROM maven:3.9.9-eclipse-temurin-21-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 \
     mvn dependency:go-offline -DskipTests -B -q

COPY src ./src

EXPOSE 8080 5005

CMD ["mvn", "spring-boot:run", \
     "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -XX:+UseG1GC -XX:MaxRAMPercentage=60.0 -XX:+UseStringDeduplication -Xss256k"]
